# Generated by Django 5.1.15 on 2026-03-31 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aqi_min', models.PositiveIntegerField()),
                ('aqi_max', models.PositiveIntegerField()),
                ('message', models.TextField()),
                ('risk_level', models.CharField(choices=[('safe', 'Safe'), ('moderate', 'Moderate'), ('high', 'High'), ('very_high', 'Very High')], max_length=20)),
            ],
            options={
                'ordering': ['aqi_min'],
            },
        ),
    ]
