# Generated by Django 5.1.15 on 2026-03-31 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=120)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
            options={
                'ordering': ['city', 'name'],
                'unique_together': {('name', 'city', 'latitude', 'longitude')},
            },
        ),
        migrations.CreateModel(
            name='AirQualityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('aqi', models.PositiveIntegerField()),
                ('pm25', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('pm10', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('source', models.CharField(choices=[('OpenAQ', 'OpenAQ'), ('WAQI', 'WAQI'), ('air.org.kz', 'air.org.kz'), ('IQAir', 'IQAir')], max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='air_quality_records', to='air_quality.location')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['source', 'timestamp'], name='air_quality_source_09001e_idx'), models.Index(fields=['latitude', 'longitude'], name='air_quality_latitud_bddae5_idx')],
            },
        ),
    ]
